### PR TITLE
[#314] 🐛 - Error merging release branch after successful deployment

### LINKED ISSUE #314: 🐛🧑‍💻 - Error merging release branch after successful deployment
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which actions are affected?

Pull Request

### Which platforms are affected?

_No response_

### Description

The release branch was merged on `master` but not on `develop`. At the end, we had an error in the procedure steps:

> Issue #ANY_ISSUE_NUM was not closed because one or more merge operations failed.

No PRs had any problem with getting merged (all checks passed), and there were no conflicts between head/base branches.

### Reproducing the issue

Create a release and add the `deploy` label. It will happen after a successful deployment.

### copilot Version

master

### Relevant Log Output

```shell

```

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by efraespada**
# 📌 Summary

Fixes an issue where the release branch merge to develop fails after a successful deployment. The problem occurred because after merging the release branch into the default branch (main/master), attempting to merge the release branch directly into develop could fail. The fix changes the second merge operation to use the default branch as the source instead of the release branch, following the same pattern used for hotfix branches.

---

## 🎯 Related Issues / Tickets

- Closes #314

---

## 🧩 Scope of Changes

- Updated: Modified the release branch merge flow in `deployed_action_use_case.ts` to merge default branch into develop (instead of release branch into develop) after the initial release-to-default merge
- Updated: Adjusted test expectations in `deployed_action_use_case.test.ts` to match the corrected merge behavior

---

## 🛠️ Technical Details

The issue occurred in the `DeployedActionUseCase` when handling release branch deployments:

**Before (buggy):**
1. Merge release branch into default branch
2. Merge release branch into develop

**After (fixed):**
1. Merge release branch into default branch
2. Merge default branch into develop

The hotfix branch flow already used this correct pattern (hotfix→main, then main→develop). The release flow has been updated to match, ensuring that after the release is merged into main, the updated main branch (which now contains all release changes) is merged into develop. This prevents merge failures that could occur when trying to merge the release branch directly into develop after it had already been merged into main.

---

## 🔍 How to Test

1. Create a release issue and add the `deploy` label to trigger the release workflow
2. After successful deployment, trigger the `deployed` single action
3. Verify that:
   - The release branch is merged into the default branch (main/master)
   - The default branch is then merged into develop
   - The issue is closed successfully when both merges complete
   - No "one or more merge operations failed" error occurs

---

## 🧪 Test Coverage

- [x] Unit tests updated to reflect the corrected merge behavior

---

## ⚠️ Breaking Changes

- None

---

## 🚀 Deployment Notes

- [x] No special deployment steps

---

## 🔒 Security Considerations

- [x] No security impact

---

## 📈 Performance Impact

- [x] No performance impact

---

## 📝 Notes for Reviewers

The key change is in line 100 of `deployed_action_use_case.ts` where the second merge operation for release branches now uses `param.branches.defaultBranch` instead of `param.currentConfiguration.releaseBranch` as the head parameter. This aligns the release branch behavior with the hotfix branch behavior, which was already correct.

---

## ✅ Checklist

- [x] I have self-reviewed my code
- [x] Code follows project standards and conventions
- [x] Tests have been added or updated
- [x] Changes are backward compatible

---

## 📚 Additional Context

The error message "Issue #ANY_ISSUE_NUM was not closed because one or more merge operations failed" was appearing even when all PR checks passed because the second merge operation (release→develop) was attempting to merge a branch that had already been merged into main, potentially causing conflicts or fast-forward issues. By merging main→develop instead, we ensure a clean merge path.

### CODE REVIEW

File: src/data/repository/merge_repository.ts [hunk 1]
```diff
@@ -61,10 +67,13 @@ This PR merges **${head}** into **${base}**.
...
+            /** Give workflows a short window to register check runs for this PR; after this, we allow merge with no check runs (e.g. branch has no required checks). */
+            const maxWaitForPrChecksAttempts = 3;
             if (timeout > iteration) {
                 // Wait for checks to complete - can use regular token for reading checks
                 let checksCompleted = false;
                 let attempts = 0;
+                let waitForPrChecksAttempts = 0;
                 const maxAttempts = timeout > iteration ? Math.floor(timeout / iteration) : iteration;
 
                 while (!checksCompleted && attempts < maxAttempts) {
```
Comment (vypbot) [inline src/data/repository/merge_repository.ts]: ## Missing attempts increment when giving up on PR check runs

**Severity:** low

**Location:** `src/data/repository/merge_repository.ts:79`

In the while loop (line 79), when check runs exist on the ref but none for this PR, and maxWaitForPrChecksAttempts is reached (lines 135-138), the code sets checksCompleted = true and continues without incrementing 'attempts'. While this exits the loop, it's inconsistent with other branches that do increment attempts. More importantly, when waitForPrChecksAttempts < maxWaitForPrChecksAttempts (lines 140-144), attempts is incremented, but if the loop exits via timeout (attempts >= maxAttempts) while still waiting for PR checks, the error message doesn't distinguish this case.
**Suggested fix:**
Consider incrementing attempts in all branches for consistency, or add a specific error message when exiting due to waitForPrChecksAttempts reaching maxWaitForPrChecksAttempts.

File: src/data/repository/merge_repository.ts [hunk 2]
```diff
@@ -74,6 +83,14 @@ This PR merges **${head}** into **${base}**.
                         ref: head,
                     });
 
+                    // Only consider check runs that are for this PR. When the same branch is used in
+                    // multiple PRs (e.g. release→master and release→develop), listForRef returns runs
+                    // for all PRs; we must wait for runs tied to the current PR or we may see completed
+                    // runs from the other PR and merge before this PR's checks have run.
+                    const runsForThisPr = (checkRuns.check_runs as Array<{ status: string; conclusion: string | null; name: string; pull_requests?: Array<{ number: number }> }>).filter(
```
Comment (vypbot) [inline src/data/repository/merge_repository.ts]: ## Type assertion bypasses type safety for check runs filtering

**Severity:** low

**Location:** `src/data/repository/merge_repository.ts:90`

At line 90, a type assertion `as Array<{ status: string; conclusion: string | null; name: string; pull_requests?: Array<{ number: number }> }>` is used to filter check runs. This bypasses TypeScript's type checking and could fail at runtime if the actual API response structure differs from the asserted type, particularly the optional `pull_requests` array.
**Suggested fix:**
Use proper type guards or validate the API response structure before filtering instead of relying on type assertions. Consider defining explicit interfaces for the expected check run structure.



<sup>Written by [vypdev/copilot](https://github.com/marketplace/actions/copilot-github-with-super-powers) for commit [8c840d810c943e8a728e049c726d3c8662be4b43](https://github.com/vypdev/copilot/commit/8c840d810c943e8a728e049c726d3c8662be4b43). This will update automatically on new commits.</sup>

File: src/utils/logger.ts [hunk 3]
```diff
@@ -9,6 +9,30 @@ export interface LogEntry {
     metadata?: Record<string, unknown>;
 }
 
+const accumulatedLogEntries: LogEntry[] = [];
```
Comment (vypbot) [inline src/utils/logger.ts]: ## Unbounded log entry accumulation without size limits

**Severity:** low

**Location:** `src/utils/logger.ts:12`

The `accumulatedLogEntries` array at line 12 grows indefinitely as logs are pushed via `pushLogEntry()`. In long-running processes or high-volume scenarios, this could lead to excessive memory consumption. There's no maximum size limit, automatic cleanup, or mechanism to prevent unbounded growth.
**Suggested fix:**
Add a maximum size limit to the accumulated logs (e.g., keep only last N entries) or implement a circular buffer pattern to prevent memory issues in long-running processes.



<sup>Written by [vypdev/copilot](https://github.com/marketplace/actions/copilot-github-with-super-powers) for commit [8c840d810c943e8a728e049c726d3c8662be4b43](https://github.com/vypdev/copilot/commit/8c840d810c943e8a728e049c726d3c8662be4b43). This will update automatically on new commits.</sup>

File: src/data/repository/merge_repository.ts [hunk 4]
```diff
@@ -111,6 +128,39 @@ This PR merges **${head}** into **${base}**.
                             attempts++;
                             continue;
                         }
+                    } else if (checkRuns.check_runs.length > 0 && runsForThisPr.length === 0) {
```
Comment (vypbot) [inline src/data/repository/merge_repository.ts]: ## Potential timeout edge case when PR check runs never appear

**Severity:** medium

**Location:** `src/data/repository/merge_repository.ts:131`

At lines 131-163, when check runs exist on the ref but none are for this PR, the code waits up to `maxWaitForPrChecksAttempts` (3) iterations before falling back to status checks. However, if workflows never register check runs for this specific PR (e.g., branch protection requires checks but workflows are misconfigured), the loop continues until `maxAttempts` is reached. This could cause unnecessary delays even when the situation is unrecoverable.
**Suggested fix:**
Consider adding a maximum wait time specifically for the PR check runs phase, or provide clearer error messaging when check runs never appear after the grace period expires.



<sup>Written by [vypdev/copilot](https://github.com/marketplace/actions/copilot-github-with-super-powers) for commit [1ee529d7911252e0c1d1d9bf862d00665859ccde](https://github.com/vypdev/copilot/commit/1ee529d7911252e0c1d1d9bf862d00665859ccde). This will update automatically on new commits.</sup>
