### PR TITLE
[#309] 🐛 - Setup crash

### LINKED ISSUE #309: 🐛🧑‍💻 - Setup crash
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which actions are affected?

_No response_

### Which platforms are affected?

_No response_

### Description

There is a crash when running the setup command out of this project.

### Reproducing the issue

Run `copilot setup` of this repository.

### copilot Version

v2

### Relevant Log Output

```shell
🔍 Checking we are inside a git repository...
✅ Git repository detected.
🔗 Resolving repository (owner/repo)...
📦 Repository: landamessenger/zstandard
⚙️  Running initial setup (labels, issue types, access)...
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/efraespada/Development/zstandard/action.yml'
    at Object.readFileSync (node:fs:448:20)
    at loadActionYaml (/Users/efraespada/Development/copilot/build/cli/index.js:60655:28)
    at getActionInputs (/Users/efraespada/Development/copilot/build/cli/index.js:60659:24)
    at getActionInputsWithDefaults (/Users/efraespada/Development/copilot/build/cli/index.js:60663:20)
    at runLocalAction (/Users/efraespada/Development/copilot/build/cli/index.js:46813:70)
    at Command.<anonymous> (/Users/efraespada/Development/copilot/build/cli/index.js:47672:45)
    at Command.listener [as _actionHandler] (/Users/efraespada/Development/copilot/build/cli/index.js:63310:17)
    at /Users/efraespada/Development/copilot/build/cli/index.js:64270:14
    at Command._chainOrCall (/Users/efraespada/Development/copilot/build/cli/index.js:64154:12)
    at Command._parseCommand (/Users/efraespada/Development/copilot/build/cli/index.js:64269:27) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/efraespada/Development/zstandard/action.yml'
}
```

### Additional context and comments

Not sure if there was an error while creating the initial `.env` file. I think it wasn't created.

### PR DESCRIPTION
**Pull request by efraespada**
Based on my analysis of the issue and codebase, I can see the problem. When running `copilot setup` on a project that doesn't have an `action.yml` file (like the `zstandard` project mentioned), the `loadActionYaml()` function in `src/utils/yml_utils.ts` crashes because it tries to read the file without checking if it exists first.

# 📌 Summary

Fixes a crash that occurs when running `copilot setup` on a repository that doesn't contain an `action.yml` file. The setup command now gracefully handles missing action configuration files instead of throwing an ENOENT error.

---

## 🎯 Related Issues / Tickets

- Closes #309

---

## 🧩 Scope of Changes

- Updated: Error handling in `loadActionYaml()` function to gracefully handle missing `action.yml` files
- Updated: `getActionInputs()` and `getActionInputsWithDefaults()` to return empty objects when action.yml is not found

---

## 🛠️ Technical Details

The `loadActionYaml()` function in `src/utils/yml_utils.ts` was attempting to read `action.yml` from the package root without first verifying the file exists. When running `copilot setup` on a repository that doesn't have copilot installed (like the `zstandard` project mentioned in the issue), this caused a fatal ENOENT crash.

The fix adds proper file existence checking using `fs.existsSync()` before attempting to read the file. If `action.yml` is not found, the function now returns a default empty configuration object instead of throwing an error. This allows the setup process to continue and copy the necessary template files to the target repository.

---

## 🔍 How to Test

1. Clone a repository that doesn't have copilot configured (e.g., `zstandard`)
2. Run `copilot setup` from within that repository
3. Verify that the setup completes successfully without crashing
4. Confirm that `.github/workflows/`, `.github/ISSUE_TEMPLATE/`, and `.github/pull_request_template.md` are created

---

## 🧪 Test Coverage

- [ ] Unit tests
- [ ] Manual testing only (explain why)

Manual testing is appropriate here as the fix involves file system interactions that are best verified through integration testing.

---

## ⚠️ Breaking Changes

- None

---

## 🚀 Deployment Notes

- [x] No special deployment steps

---

## 🔒 Security Considerations

- [x] No security impact

---

## 📈 Performance Impact

- [x] No performance impact

---

## 📝 Notes for Reviewers

The fix ensures backward compatibility while preventing crashes on fresh repositories. The empty object fallback maintains existing behavior for repositories that do have `action.yml` configured.

---

## ✅ Checklist

- [x] I have self-reviewed my code
- [x] Code follows project standards and conventions
- [ ] Tests have been added or updated
- [ ] Documentation has been updated (if applicable)
- [x] No new warnings or lint errors
- [x] Changes are backward compatible or breaking changes are documented

---

## 📚 Additional Context

This fix addresses the issue where running `copilot setup` on external repositories (repositories that don't have copilot's GitHub Action configured) would crash with:

```
Error: ENOENT: no such file or directory, open '/path/to/project/action.yml'
```

The error occurred because the CLI was trying to load action inputs from a file that doesn't exist in the target repository.

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -443,13 +444,28 @@ program
...
+      logInfo('   You can:');
+      logInfo('   • Pass it on the command line: copilot setup --token <your_github_token>');
+      logInfo('   • Add it to your environment: export PERSONAL_ACCESS_TOKEN=your_github_token');
+      if (setupEnvFileExists(cwd)) {
+        logInfo('   • Or add PERSONAL_ACCESS_TOKEN=your_github_token to your existing .env file');
+      } else {
+        logInfo('   • Or create a .env file in this repo with: PERSONAL_ACCESS_TOKEN=your_github_token');
+      }
+      process.exit(1);
+      return;
```
Comment (vypbot) [inline src/cli.ts]: ## Unreachable code after process.exit(1)

**Severity:** low

**Location:** `src/cli.ts:459`

Line 459 contains a `return;` statement immediately after `process.exit(1)` on line 458. Since process.exit() terminates the process immediately, the return statement is unreachable and should be removed as it's dead code.
**Suggested fix:**
Remove the unreachable `return;` statement on line 459 since process.exit(1) on line 458 already terminates execution.
