### PR TITLE
[#324] 🐛 - Wrong tag names

### LINKED ISSUE #324: 🐛🧑‍💻 - Wrong tag names
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which actions are affected?

_No response_

### Which platforms are affected?

_No response_

### Description

Maybe new tags are created over the wrong branch:

The tag `v.2.0.4` should be created over `release/2.0.4`, not `master.`

Another tag is created as `2.0.4` (without the `v`) from `release/2.0.4`.

Only one tag should be created as, for example `v.2.0.4`, from `release/2.0.4`.

### Reproducing the issue

Create a deploy a new release.

### copilot Version

master

### Relevant Log Output

```shell

```

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by efraespada**
# Summary

Fix release tag generation to use the correct source branch and consistent naming. Tags are now created from release/2.0.4 (not from master) and follow a single, prefixed naming convention (e.g., v.2.0.4). This prevents creation of unintended tags such as 2.0.4 and ensures only one tag is produced per release.

---

## Related Issues

- Closes #324
- Related to #324 (branch/tag naming inconsistencies during releases)

---

## Scope of Changes

- Updated release tagging logic to:
  - Use the corresponding release branch (e.g., release/2.0.4) as the source for tag creation.
  - Enforce a single tag name format with a v-prefix (e.g., v.2.0.4).
  - Prevent creation of tags from non-release branches (e.g., master).
  - Add idempotent checks to avoid duplicate tags.
- Adjusted CI/workflow steps to align with the corrected tagging process.
- Updated release-related documentation to reflect the corrected tagging policy.

---

## Technical Details

- Root cause: tagging script/CI workflow derived tags from the wrong base branch (master) and allowed a non-prefixed tag (2.0.4), resulting in multiple or conflicting tags for a single release.
- Solution:
  - Bind tag creation to the specific release branch provided (e.g., release/2.0.4).
  - Normalize tag naming to a single, consistent format with a v-prefix (v.2.0.4).
  - Add guards to skip tag creation if the tag already exists.
  - Update CI to validate and restrict tagging to release branches only.
- Trade-offs:
  - Slightly tighter CI preconditions for tagging; simpler tag namespace and more predictable releases.
  - No user-facing API changes; purely release automation improvement.

---

## How to Test

- Local/manual testing:
  1. Ensure you are on a clean working tree and up to date with develop.
  2. Trigger the tagging logic with a release branch, e.g. release/2.0.4:
     - Run the tagging script or workflow that was updated.
     - Confirm that a single tag named v.2.0.4 is created from release/2.0.4.
     - Verify that no tag named 2.0.4 (without the v) is produced.
     - Attempt to run again; ensure no duplicate tag is created (idempotence).
  3. Push changes and observe CI:
     - Open a PR from bugfix/324-wrong-tag-names to develop.
     - Confirm CI steps validate the release branch and that the tagging step uses the correct base.
- Remote/state verification:
  - After tagging, run: git fetch --tags; git tag -l "v.*" to confirm only the expected tag exists for the release.
  - Ensure the tag points to the commit corresponding to release/2.0.4.

---

## Test Coverage / Deployment / Security / Performance / Checklist

- [x] Tests updated or added for tag naming logic
- [x] Documentation updated (release process / tagging policy)
- [x] CI workflow updated to enforce branch-based tagging
- [x] Manual testing steps provided
- [ ] Security
- [ ] Performance
- [ ] Other

---

## Breaking Changes

None. This is an automation fix for release tagging and does not alter runtime code or public APIs.

---

## Notes for Reviewers / Additional Context

- The change aligns tag creation with the intended release workflow: one tag per release from the release branch, with a consistent v-prefix.
- If there are other release branches (e.g., release/2.1.0), the same pattern will apply; tagging will derive from the respective release branches only.

### CODE REVIEW

File: src/usecase/actions/create_release_use_case.ts [hunk 1]
```diff
@@ -42,6 +42,7 @@ export class CreateReleaseUseCase  implements ParamUseCase<Execution, Result[]>
                     ],
```
Comment (vypbot) [inline src/usecase/actions/create_release_use_case.ts:64]: ## Potential release version format not validated

**Severity:** medium

**Location:** `src/usecase/actions/create_release_use_case.ts`

CreateReleaseUseCase validates that version, title, and changelog are non-empty, but there is no validation of the actual format of the version string before constructing the release tag (prefixing with 'v'). If an invalid version is supplied (e.g., non-numeric, includes a leading 'v'), the generated release tag may be malformed (e.g., 'vv1.2.3').
**Suggested fix:**
Validate the version string against a semantic version pattern (e.g., /^(\d+)(?:\.(\d+)){0,2}$|^\d+\.\d+\.\d+$/) or use a semver library, and ensure the 'v' prefix is applied consistently only after validation.



<sup>Written by [vypdev/copilot](https://github.com/marketplace/actions/copilot-github-with-super-powers) for commit [a52be8edfc225ef2e69259e13b5576198f9ab65d](https://github.com/vypdev/copilot/commit/a52be8edfc225ef2e69259e13b5576198f9ab65d). This will update automatically on new commits.</sup>
